#!/bin/zsh

# Allows you to search all of your commands history
# Usage:
# 
#  history-grep npm run
#
#  ^ will search all command history for "npm run"

history-grep() {
  line_length_default="200"
  : "${LINE_LENGTH:=$line_length_default}"
  # ^ Assigns default value if LINE_LENGTH is not defined in environment
  found_lines=$(grep "$@" ~/.zsh_history | cut -b 1-$LINE_LENGTH)
  while IFS= read -r line; do
    timestamp=$(echo "$line" | cut -d ':' -f 2)
    cmd=$(echo "$line" | cut -d ';' -f 2)

    # OS specific
    case "$OSTYPE" in
    # Mac
    darwin*)
      human_date=$(date -r "$timestamp" '+%Y-%m-%d %H:%M:%S')
      ;;
    # Linux
    linux*)
      human_date=$(date -d "@$timestamp" '+%Y-%m-%d %H:%M:%S')
      ;;
    esac

    echo "<$human_date> $cmd"
  done <<< "$found_lines"
}
