#!/bin/zsh

# Kills a process running on a specified tcp port
killport() {
  echo "> Killing process on port: $1"

  NC='\033[0m'        # Text Reset
  GREY='\033[0;30m'   # Text Gray

  # OS specific
  case "$OSTYPE" in
  # Mac
  darwin*)
    PROCESS_ID=$(lsof -ti:$1)
    if [ ! -z "$PROCESS_ID" ]; then 
      kill -9 $PROCESS_ID
    else;
      echo " - no process running on port $1"
    fi
    ;;
  # Linux
  linux*)
    PROCESS_ID=$(fuser -v -n tcp $1);
    if [ ! -z "$PROCESS_ID" ]; then 
      fuser -n tcp -k $1;
    else;
      echo " - no process running on port $1"
      printf " ${GREY}    try these sudo commands:
      sudo lsof -i tcp:$1 
      sudo fuser -n tcp -k $1
${NC}"
    fi
    ;;
  esac
}
