#!/bin/zsh

# Kills a process running on a specified tcp port
killport() {
  echo "> Killing process on port: $1"

  # OS specific
  case "$OSTYPE" in
  # Mac
  darwin*)
    PROCESS_ID=$(lsof -ti:$1)
    if [ ! -z "$PROCESS_ID" ]; then 
      kill -9 $PROCESS_ID
    else;
      echo " - no process running on port $1"
    fi
    ;;
  # Linux
  linux*)
    echo "--- CHECK THE FOLLOWING CODE WORKS ---"
    PROCESS_ID=$(fuser -v -n tcp $1);
    if [ ! -z "$PROCESS_ID" ]; then 
      fuser -n tcp -k $1;
    else;
      echo " - no process running on port $1"
    fi
    ;;
  esac
}
