#!/bin/zsh

# Retry a command.
function retry_untilfail() {
  echo "Running \"${@:1}\" with auto-retry..."
  iteration=1

  while ${@:1} ; do
    iteration=$((iteration+1))
    echo "didn't fail, so waiting 1s then trying again (iteration=$iteration)..."
    sleep 1
  done
}